### ISSUE TITLE
Can't Install On Debian Due To Failed Package Depdency

### ISSUE THREAD

**Issue by StrangeWill** [Siteminds/puppet-gogs#5]
Need apt-transport-https for the SSL based repository.

**Comment by bjwschaap** [comment]
Valid issue! Do you have a pull request lined up @StrangeWill ? Otherwise I'll test and implement this within the next couple of weeks.

**Comment by StrangeWill** [comment]
I'll see about getting something together, I got some other minor issues that I'll report once I have a clean VM to stand up again and again.
